### ISSUE TITLE
version variable name conflict with spring-boot-dependencies

### ISSUE THREAD

**Issue by LayGit** [hugegraph/hugegraph-client#53]
eg.
spring-boot-dependencies 2.1.1.RELEASE contains version variable
`<jersey.version>2.27</jersey.version>`
and hugegraph-client 1.7.3 contains the same name variable
`<jersey.version>2.22</jersey.version>`

so maven uses the 2.27 version of jersey, it caused exception
`java.lang.NoClassDefFoundError: javax/ws/rs/client/RxInvokerProvider`

**Comment by LayGit** [comment]
cannot work with fastjson 1.2.36+ [#1392](https://github.com/alibaba/fastjson/issues/1392)

**Comment by zhoney** [comment]
Not bug of HugeGraph components and no comments for a long time. Close it. If there are more comments about this issue, just reopen it please.
